FROM node:14.5.0

# add `/app/node_modules/.bin` to $PATH

WORKDIR '/app'
ENV PATH /app/node_modules/.bin:$PATH
# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g --silent

##COPY . .
##CMD ["npm", "run", "start"]
##EXPOSE 3000
